#!/usr/bin/env python3
"""Build the game's static data tables from the YAML files in data/.

Usage:
    datagen.py OUTDIR       write partids.h and data_tables.c into OUTDIR

Each YAML file is a list of entries, one per element of a C array (a list
of lists for a two-dimensional one). An entry is written out as a C
designated initializer: its keys are the struct's field names and its
values are C values.

    - name: iengineFuelMizer        # its enum value in partids.h
      szName: "Fuel Mizer"          # sz keys are strings (Windows-1252)
      rgwtOreCost: [8]              # lists become {8}
      grfAbilities: engineFuelMizer # other strings are C expressions
      hul: {...}                    # maps become nested initializers

Two more forms follow the Hungarian prefixes:

      rgAttr: {rsResGen: 10}        # an rg map sets elements: {[rsResGen] = 10}
      grbitAttr: [grbitRaceIFE, grbitRaceTT]   # a grbit or grf list is ORed

The compiler checks the field names, enum values and types, so this script
knows nothing of the structs. Fields left out are zero. Only keys starting
with f may hold true/false, and a string too long for its sz field fails a
static assertion. Only tables that define an enum have a name per entry.

An entry's position in its file is its enum value. Code uses the names, but
saved ship designs store hull and part numbers, so the parts files are
append-only: reordering or removing an entry would load 2.6j and 2.8 designs
with the wrong parts. The regression's checkpoints hold such designs and
would show it. Code that uses a renamed entry's old name no longer compiles.

Fields the generator fills in, which the YAML must not set:
    id           COMPART tables: the position + 1
    hul.ihuldef  hulls: the hull's HulDef
    hul.chs      the number of hul.rghs slots
    iplan        battle plans: the position
"""

import os
import re
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write("datagen: the build needs PyYAML (python3 -m pip install pyyaml)\n")
    sys.exit(1)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

GENERATED = "Generated by data/datagen.py from data/{}. Do not edit."

def Parts(file, ctype, array, enum, count, prefix, derive=None):
    return dict(file="parts/" + file, ctype=ctype, array=array, enum=enum, count=count, prefix=prefix, derive=derive)


# The tables, with their enums in the order they appear in partids.h.
# Starbase hulls continue HulDef after the ship hulls: each has an isbhull
# name and a HulDef name (huldef). shape gives a two-dimensional table's size.
TABLES = [
    Parts("hulls.yaml", "HULDEF", "rghuldef", "HulDef", None, "ihuldef", "hull"),
    Parts("starting-starbases.yaml", "SHDEF", "rgshdefSBT", "StartingStarbase", None, ""),
    Parts("starting-ships.yaml", "SHDEF", "rgshdefT", "StartingShip", None, ""),
    Parts("starbase-hulls.yaml", "HULDEF", "rghuldefSB", "isbhull", "isbhullCount", "isbhull", "starbase hull"),
    Parts("engines.yaml", "ENGINE", "rgengine", "iengine", "iengineCount", "iengine", "id"),
    Parts("armor.yaml", "ARMOR", "rgarmor", "iarmor", "iarmorCount", "iarmor", "id"),
    Parts("scanners.yaml", "SCANNER", "rgscanner", "iscanner", "iscannerCount", "iscanner", "id"),
    Parts("shields.yaml", "SHIELD", "rgshield", "ishield", "ishieldCount", "ishield", "id"),
    Parts("electrical.yaml", "SPECIAL", "rgspecialE", "ispecialE", "ispecialECount", "ispecialE", "id"),
    Parts("mechanical.yaml", "SPECIAL", "rgspecialM", "ispecialM", "ispecialMCount", "ispecialM", "id"),
    Parts("mine-layers.yaml", "MINES", "rgmines", "imines", "iminesCount", "imines", "id"),
    Parts("mining-robots.yaml", "MINING", "rgmining", "imining", "iminingCount", "imining", "id"),
    Parts("planetary.yaml", "PLANETARY", "rgplanetary", "iplanetary", "iplanetaryCount", "iplanetary", "id"),
    Parts("terraformers.yaml", "TERRA", "rgterra", "iterra", "iterraCount", "iterra", "id"),
    Parts("bombs.yaml", "BOMB", "rgbomb", "ibomb", "ibombCount", "ibomb", "id"),
    Parts("torpedoes.yaml", "TORP", "rgtorp", "itorp", "itorpCount", "itorp", "id"),
    Parts("beams.yaml", "BEAM", "rgbeam", "ibeam", "ibeamCount", "ibeam", "id"),
    Parts("starbase-specials.yaml", "SPECIALSB", "rgspecialSB", "ispecialSB", "ispecialSBCount", "ispecialSB", "id"),
    dict(file="battle-plans.yaml", ctype="BTLPLAN", array="rgbtlplanT", derive="iplan"),
    dict(file="races/predefined.yaml", ctype="PLAYER", array="vrgplrDef"),
    dict(file="races/ai.yaml", ctype="PLAYER", array="vrgplrComp", shape=(6, 4)),
]

IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
# A C value other than a number or string: names, |, +, -, shifts, parens.
EXPR = re.compile(r"[A-Za-z0-9_ |+\-<>()~]+\Z")


class DataError(Exception):
    pass


def CString(s, where):
    try:
        raw = s.encode("cp1252")
    except UnicodeEncodeError:
        raise DataError("{}: {!r} is not Windows-1252".format(where, s))
    out = []
    for b in raw:
        if b in (0x22, 0x5C):
            out.append("\\" + chr(b))
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\{:03o}".format(b))
    return '"' + "".join(out) + '"'


def CValue(key, value, where, asserts, path):
    """Return the C initializer for one YAML value."""
    if isinstance(value, bool):
        if not key.startswith("f"):
            raise DataError("{}: {} is true/false; only f keys are flags (quote a name like 'no')".format(where, key))
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        if key.startswith("sz"):
            lit = CString(value, where)
            asserts.append('_Static_assert(sizeof({0}) <= sizeof({1}), "{1} is too long");'.format(lit, path))
            return lit
        if not EXPR.match(value):
            raise DataError("{}: {}: {!r} is not a C value".format(where, key, value))
        return value
    if key.startswith("sz"):
        raise DataError("{}: {} must be a string".format(where, key))
    if isinstance(value, list) and key.startswith(("grbit", "grf")):
        for v in value:
            if not isinstance(v, str) or not IDENT.match(v):
                raise DataError("{}: {}: {!r} is not a flag name".format(where, key, v))
        return " | ".join(value) or "0"
    if isinstance(value, dict) and key.startswith("rg"):
        items = []
        for k, v in value.items():
            if not isinstance(k, (str, int)) or isinstance(k, bool) or not EXPR.match(str(k)):
                raise DataError("{}: {}: {!r} is not an index".format(where, key, k))
            items.append("[{}] = {}".format(k, CValue(key, v, where, asserts, "{}[{}]".format(path, k))))
        return "{" + ", ".join(items) + "}"
    if isinstance(value, list):
        items = []
        for i, v in enumerate(value):
            pathItem = "{}[{}]".format(path, i)
            # A map in a list is a struct, as in rghs: [{grhst: hstEngine}].
            items.append(CStruct(v, where, asserts, pathItem) if isinstance(v, dict) else CValue(key, v, where, asserts, pathItem))
        return "{" + ", ".join(items) + "}"
    if isinstance(value, dict):
        return CStruct(value, where, asserts, path)
    raise DataError("{}: {}: unsupported value {!r}".format(where, key, value))


def CStruct(fields, where, asserts, path, indent=None):
    items = []
    for key, value in fields.items():
        if not isinstance(key, str) or not IDENT.match(key):
            raise DataError("{}: {!r} is not a field name".format(where, key))
        items.append(".{} = {}".format(key, CValue(key, value, where, asserts, "{}.{}".format(path, key))))
    if indent is None:
        return "{" + ", ".join(items) + "}"
    return "{\n" + "".join("{}{},\n".format(indent, item) for item in items) + indent[:-4] + "}"


def LoadTable(table):
    file = table["file"]
    prefix = table.get("prefix")
    derive = table.get("derive")
    with open(os.path.join(HERE, file), encoding="utf-8") as f:
        entries = yaml.safe_load(f)
    shape = table.get("shape")
    if shape:
        if not isinstance(entries, list) or len(entries) != shape[0] or any(
            not isinstance(row, list) or len(row) != shape[1] for row in entries
        ):
            raise DataError("data/{}: expected {} lists of {} entries".format(file, *shape))
        entries = [entry for row in entries for entry in row]
    elif not isinstance(entries, list) or not entries:
        raise DataError("data/{}: expected a list of entries".format(file))
    for i, entry in enumerate(entries):
        where = "data/{}: entry {}".format(file, i)
        if not isinstance(entry, dict):
            raise DataError("{}: expected a map".format(where))
        if prefix is not None:
            name = entry.get("name")
            if not isinstance(name, str) or not IDENT.match(name) or not name.startswith(prefix):
                raise DataError("{}: name {!r} must be a C name starting with {!r}".format(where, name, prefix))
        derived = {"id": ("id",), "iplan": ("iplan",)}.get(derive, ())
        for key in derived:
            if key in entry:
                raise DataError("{}: {} is generated from the position; remove it".format(where, key))
        hul = entry.get("hul")
        if isinstance(hul, dict):
            for key in ("chs",) + (("ihuldef",) if derive in ("hull", "starbase hull") else ()):
                if key in hul:
                    raise DataError("{}: hul.{} is generated; remove it".format(where, key))
        if derive == "starbase hull" and not IDENT.match(str(entry.get("huldef", ""))):
            raise DataError("{}: starbase hulls need huldef, their HulDef name".format(where))
    return entries


def Generate(outdir):
    header = [
        "// " + GENERATED.format("parts/*.yaml"),
        "// The part, hull and starting design indexes, included by enums.h.",
        "#ifndef STARS_PARTIDS_H",
        "#define STARS_PARTIDS_H",
        "",
    ]
    body = ["// " + GENERATED.format("*.yaml"), '#include "common.h"', ""]
    asserts = []
    tables = {table["array"]: LoadTable(table) for table in TABLES}
    rgHulDef = [e["name"] for e in tables["rghuldef"]] + [e["huldef"] for e in tables["rghuldefSB"]]
    for table in TABLES:
        array = table["array"]
        entries = tables[array]
        derive = table.get("derive")
        enum = table.get("enum")
        if enum:
            names = rgHulDef if enum == "HulDef" else [e["name"] for e in entries]
            header.append("enum {} {{".format(enum))
            header += ["    {} = {},".format(name, i) for i, name in enumerate(names)]
            if table["count"]:
                header.append("    {} = {},".format(table["count"], len(names)))
            header += ["};", ""]
        shape = table.get("shape") or (len(entries),)
        rgsz = []
        for i, entry in enumerate(entries):
            iRow, iCol = divmod(i, shape[1]) if len(shape) == 2 else (i, None)
            index = "[{}]".format(i) if iCol is None else "[{}][{}]".format(iRow, iCol)
            where = "data/{}: {}".format(table["file"], entry["name"] if enum else "entry " + index)
            fields = {k: v for k, v in entry.items() if not (enum and k in ("name", "huldef"))}
            if derive == "id":
                fields = dict(id=i + 1, **fields)
            elif derive == "iplan":
                fields = dict(iplan=i, **fields)
            hul = fields.get("hul")
            if isinstance(hul, dict):
                hul = dict(hul)
                if derive == "hull":
                    hul = dict(ihuldef=entry["name"], **hul)
                elif derive == "starbase hull":
                    hul = dict(ihuldef=entry["huldef"], **hul)
                if "rghs" in hul:
                    hul["chs"] = len(hul["rghs"])
                fields["hul"] = hul
            rgsz.append("    /* {} */ {}".format(index, CStruct(fields, where, asserts, array + index, " " * 8)))
        if len(shape) == 2:
            rows = [",\n".join(rgsz[r * shape[1] : (r + 1) * shape[1]]) for r in range(shape[0])]
            init = ",\n".join("{{\n{}\n}}".format(row) for row in rows)
        else:
            init = ",\n".join(rgsz)
        dims = "".join("[{}]".format(n) for n in shape)
        body.append("{} {}{} = {{\n{}\n}};\n".format(table["ctype"], array, dims, init))
    header += ["#endif", ""]
    body += asserts + [""]
    os.makedirs(outdir, exist_ok=True)
    for name, text in (("partids.h", "\n".join(header)), ("data_tables.c", "\n".join(body))):
        WriteIfChanged(os.path.join(outdir, name), text)


def WriteIfChanged(path, text):
    try:
        with open(path, encoding="ascii", newline="") as f:
            if f.read() == text:
                return
    except FileNotFoundError:
        pass
    with open(path, "w", encoding="ascii", newline="") as f:
        f.write(text)


def main(argv):
    if len(argv) != 1 or argv[0].startswith("-"):
        sys.stderr.write(__doc__.split("\n\n")[1] + "\n")
        return 2
    try:
        Generate(argv[0])
    except DataError as e:
        sys.stderr.write("datagen: {}\n".format(e))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
