# Generates version.h from git. Run at build time with:
#   cmake -DSOURCE_DIR=... -DOUTPUT=... -DVERSION_BASE=X.Y.Z -P version.cmake
#
# A clean checkout of a vX.Y.Z tag is release X.Y.Z, build 0. Any other commit
# is a development build of the next version, numbered by its distance from
# the last vX.Y.Z tag (or from 2.6jrc3 before the first one):
#   2.8.0-dev.12+g1a2b3c4        12 commits after the last release
#   2.8.0-dev.12+g1a2b3c4.dirty  with uncommitted changes
# The next version is VERSION_BASE, or the last tag's patch + 1 if that is
# higher, so a release never needs a version bump commit.
# Set STARS_VERSION in the environment to override (for source archives).
#
# The name shown to players is MAJOR.MINORx64, the 64-bit Win32 build, with
# the full version after it unless this is the X.Y.0 release:
#   2.8x64                                  release 2.8.0
#   2.8x64 (2.8.1-dev.12+g1a2b3c4)          development build

cmake_minimum_required(VERSION 3.23)

function(stars_git out)
    execute_process(COMMAND git ${ARGN}
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE value
        RESULT_VARIABLE result
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(result EQUAL 0)
        set(${out} "${value}" PARENT_SCOPE)
    else()
        set(${out} "" PARENT_SCOPE)
    endif()
endfunction()

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$" match "${VERSION_BASE}")
if(NOT match)
    message(FATAL_ERROR "VERSION_BASE must be X.Y.Z, got '${VERSION_BASE}'")
endif()
set(major ${CMAKE_MATCH_1})
set(minor ${CMAKE_MATCH_2})
set(patch ${CMAKE_MATCH_3})
set(build 0)
set(commit "unknown")
set(release FALSE)
set(dirty "")

if(DEFINED ENV{STARS_VERSION} AND NOT "$ENV{STARS_VERSION}" STREQUAL "")
    set(text "$ENV{STARS_VERSION}")
    if(NOT text MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)")
        message(FATAL_ERROR "STARS_VERSION must start with X.Y.Z, got '${text}'")
    endif()
    set(major ${CMAKE_MATCH_1})
    set(minor ${CMAKE_MATCH_2})
    set(patch ${CMAKE_MATCH_3})
else()
    stars_git(head rev-parse --short=7 HEAD)
    if(head)
        set(commit "${head}")
        stars_git(status status --porcelain --untracked-files=no)
        if(status)
            set(dirty ".dirty")
        endif()
        stars_git(described describe --tags --long --abbrev=7 --match "v[0-9]*.[0-9]*.[0-9]*" HEAD)
        if(described MATCHES "^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-([0-9]+)-g[0-9a-f]+$")
            set(tag_version "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}")
            set(build ${CMAKE_MATCH_4})
            if(build EQUAL 0 AND NOT dirty)
                set(release TRUE)
                set(major ${CMAKE_MATCH_1})
                set(minor ${CMAKE_MATCH_2})
                set(patch ${CMAKE_MATCH_3})
            else()
                math(EXPR next_patch "${CMAKE_MATCH_3} + 1")
                set(next "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${next_patch}")
                if(next VERSION_GREATER VERSION_BASE)
                    set(major ${CMAKE_MATCH_1})
                    set(minor ${CMAKE_MATCH_2})
                    set(patch ${next_patch})
                endif()
            endif()
        else()
            stars_git(count rev-list --count 2.6jrc3..HEAD)
            if(count STREQUAL "")
                stars_git(count rev-list --count HEAD)
            endif()
            if(NOT count STREQUAL "")
                set(build ${count})
            endif()
        endif()
    endif()
    if(release)
        set(text "${major}.${minor}.${patch}")
    else()
        set(text "${major}.${minor}.${patch}-dev.${build}+g${commit}${dirty}")
    endif()
endif()

set(display "${major}.${minor}x64")
if(NOT text STREQUAL "${major}.${minor}.0")
    set(display "${display} (${text})")
endif()

set(content "/* Generated by cmake/version.cmake. Do not edit. */
#ifndef STARS_VERSION_H
#define STARS_VERSION_H

#define STARS_VERSION_MAJOR  ${major}
#define STARS_VERSION_MINOR  ${minor}
#define STARS_VERSION_PATCH  ${patch}
#define STARS_VERSION_BUILD  ${build}
#define STARS_VERSION_STRING \"${text}\"
#define STARS_VERSION_DISPLAY \"${display}\"
#define STARS_VERSION_COMMIT \"${commit}\"

#endif
")

if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
else()
    set(previous "")
endif()
if(NOT previous STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
    message(STATUS "Stars! version ${display}")
endif()
