#!/usr/bin/env python3
"""Build the game's compressed text tables from the sources in text/.

Usage:
    textgen.py OUTDIR             write textids.h and text_*.c into OUTDIR
    textgen.py --unreferenced     list rows no source names and no @range covers

Each table is a text file of rows, one string per row:

    ID NAME "TEXT"          strings.txt, tutorial.txt
    ID NAME ARGS "TEXT"     messages.txt (ARGS: the parameters it formats)
    "TEXT"                  planets.txt (the row's position is its index)

TEXT runs from the first to the last double quote on the line and is taken
as written: a backslash is a backslash, as in the \\p and \\v00 format codes.
Lines starting with # are comments.

IDs are fixed. A row's ID is its index in the table and its NAME becomes an
enum value in textids.h, so deleting a row leaves a gap (an empty string)
rather than renumbering the rows after it. Code that still names a deleted
row no longer compiles. Message and planet-name indexes are also stored in
game files, which is another reason they must not move.

Some rows are reached only by arithmetic from a named row (idsHumanoid + i).
"@range COUNT [note]" before a run of rows says the next COUNT rows are used
that way: they must stay together with consecutive IDs, and deleting one is
a build error. The tutorial is a range of eight fragments per page.

The encoding is the original game's. Characters are ranked by frequency into
a lookup table; a character of rank r is written as r / 15 nibbles of 15 and
then one nibble of r % 15. Strings are packed nibble to nibble in chunks of
64 that each start on a byte; acXXX holds each string's length in nibbles and
aiXXXChunkOffset each chunk's first byte. The decoders are
PszGetCompressedString (strings.c), PszGetCompressedMessage (msg.c),
CchTutorString (tutor2.c) and PszGetCompressedPlanet (utilgen.c).
"""

import collections
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

CHUNK = 64  # Strings per chunk; the decoders shift by 6.
MAX_NIBBLES = 255  # acXXX holds lengths in a byte.

# (file, array tag, ID prefix, enum, ID format, has message args, output,
# the header that declares the tables). The tutorial is UI code (win.h).
TABLES = [
    ("strings.txt", "STR", "ids", "StringId", "0x{:04x}", False, "text_strings.c", "common.h"),
    ("messages.txt", "MSG", "idm", "MessageId", "0x{:04x}", True, "text_messages.c", "common.h"),
    ("tutorial.txt", "TUT", "idt", "TutorId", "{}", False, "text_tutorial.c", "win.h"),
    ("planets.txt", "PN", None, None, None, False, "text_planets.c", "common.h"),
]

GENERATED = "Generated by text/textgen.py from text/{}. Do not edit."


class TextError(Exception):
    pass


class Row:
    def __init__(self, id, name, args, text, line):
        self.id = id
        self.name = name
        self.args = args
        self.text = text
        self.line = line


def ParseTable(path, prefix, fArgs):
    """Return the rows of one text file, checking IDs, names and ranges."""
    rows = []
    ranges = []  # [count, note, line, rows]
    rangeOpen = None
    names = {}
    fname = os.path.relpath(path, ROOT)
    with open(path, encoding="ascii", newline="") as f:
        lines = f.read().split("\n")
    for iLine, line in enumerate(lines, 1):
        line = line.rstrip("\r")
        where = "{}:{}".format(fname, iLine)
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("@range"):
            m = re.fullmatch(r"@range\s+(\d+)(?:\s+(.*))?", stripped)
            if not m or int(m.group(1)) < 1:
                raise TextError("{}: expected @range COUNT [note]".format(where))
            if rangeOpen and len(rangeOpen[3]) < rangeOpen[0]:
                raise TextError(
                    "{}: @range at line {} has {} of its {} rows".format(where, rangeOpen[2], len(rangeOpen[3]), rangeOpen[0])
                )
            rangeOpen = [int(m.group(1)), m.group(2) or "", iLine, []]
            ranges.append(rangeOpen)
            continue
        iQuote = line.find('"')
        if iQuote < 0 or line.rfind('"') == iQuote:
            raise TextError('{}: expected the text in double quotes'.format(where))
        text = line[iQuote + 1 : line.rfind('"')]
        if line[line.rfind('"') + 1 :].strip():
            raise TextError("{}: unexpected text after the closing quote".format(where))
        for ch in text:
            if not " " <= ch <= "~":
                raise TextError("{}: text may hold only printable ASCII, not {!r}".format(where, ch))
        fields = line[:iQuote].split()
        if prefix is None:
            if fields:
                raise TextError("{}: expected only the text in double quotes".format(where))
            row = Row(len(rows), None, None, text, iLine)
        else:
            if len(fields) != (3 if fArgs else 2):
                raise TextError(
                    "{}: expected ID NAME{} \"TEXT\"".format(where, " ARGS" if fArgs else "")
                )
            try:
                id = int(fields[0], 0)
            except ValueError:
                raise TextError("{}: bad ID {!r}".format(where, fields[0]))
            name = fields[1]
            if not re.fullmatch(prefix + r"[A-Za-z0-9_]+", name):
                raise TextError("{}: {!r} is not a name starting with {}".format(where, name, prefix))
            if name in names:
                raise TextError("{}: {} is also defined at line {}".format(where, name, names[name]))
            names[name] = iLine
            if rows and id <= rows[-1].id:
                raise TextError("{}: ID {} must be greater than the previous row's {}".format(where, fields[0], rows[-1].id))
            if id >= 0xFFFF:
                raise TextError("{}: ID {} is out of range".format(where, fields[0]))
            args = None
            if fArgs:
                if not fields[2].isdigit():
                    raise TextError("{}: bad ARGS {!r}".format(where, fields[2]))
                args = int(fields[2])
            row = Row(id, name, args, text, iLine)
        if rangeOpen and len(rangeOpen[3]) < rangeOpen[0]:
            if rangeOpen[3] and row.id != rangeOpen[3][-1].id + 1:
                raise TextError(
                    "{}: ID {} leaves a gap in the @range at line {} ({}); its rows must stay together".format(
                        where, fields[0], rangeOpen[2], rangeOpen[1] or "no note"
                    )
                )
            rangeOpen[3].append(row)
        rows.append(row)
    if rangeOpen and len(rangeOpen[3]) < rangeOpen[0]:
        raise TextError(
            "{}: @range at line {} has {} of its {} rows".format(fname, rangeOpen[2], len(rangeOpen[3]), rangeOpen[0])
        )
    return rows, ranges


def Encode(rows):
    """Return (compressed bytes, nibble lengths, chunk offsets, lookup table)."""
    cTable = rows[-1].id + 1 if rows else 0
    rgsz = [""] * cTable
    for row in rows:
        rgsz[row.id] = row.text
    count = collections.Counter("".join(rgsz))
    # Most frequent first; ties by character code so the output is stable.
    lookup = sorted(count, key=lambda ch: (-count[ch], ord(ch)))
    rank = {ch: i for i, ch in enumerate(lookup)}
    rgbOut = bytearray()
    rgcLen = []
    rgiChunk = []
    nibbles = []
    for ids, sz in enumerate(rgsz):
        if ids % CHUNK == 0:
            if len(nibbles) % 2:
                nibbles.append(0)
            rgbOut += bytes(nibbles[i] << 4 | nibbles[i + 1] for i in range(0, len(nibbles), 2))
            nibbles = []
            rgiChunk.append(len(rgbOut))
        cBefore = len(nibbles)
        for ch in sz:
            r = rank[ch]
            nibbles += [15] * (r // 15) + [r % 15]
        cLen = len(nibbles) - cBefore
        if cLen > MAX_NIBBLES:
            raise TextError("ID {} needs {} nibbles; a string may use at most {}".format(ids, cLen, MAX_NIBBLES))
        rgcLen.append(cLen)
    if len(nibbles) % 2:
        nibbles.append(0)
    rgbOut += bytes(nibbles[i] << 4 | nibbles[i + 1] for i in range(0, len(nibbles), 2))
    if rgbOut and rgiChunk[-1] > 0x7FFF:
        raise TextError("compressed text passes 32K, beyond the int16_t chunk offsets")
    return bytes(rgbOut), rgcLen, rgiChunk, [ord(ch) for ch in lookup]


def FormatArray(decl, values):
    lines = []
    for i in range(0, len(values), 20):
        lines.append("    " + ", ".join(str(v) for v in values[i : i + 20]) + ",")
    return "{} = {{\n{}\n}};\n".format(decl, "\n".join(lines))


def Signed(b):
    return b - 256 if b > 127 else b


def WriteIfChanged(path, text):
    try:
        with open(path, encoding="ascii", newline="") as f:
            if f.read() == text:
                return
    except FileNotFoundError:
        pass
    with open(path, "w", encoding="ascii", newline="") as f:
        f.write(text)


def Generate(outdir):
    header = [
        "// " + GENERATED.format("*.txt"),
        "// The IDs of the game's text, included by enums.h.",
        "#ifndef STARS_TEXTIDS_H",
        "#define STARS_TEXTIDS_H",
        "",
    ]
    outputs = {}
    for file, tag, prefix, enum, fmtId, fArgs, output, include in TABLES:
        rows, _ = ParseTable(os.path.join(HERE, file), prefix, fArgs)
        if not rows:
            raise TextError("text/{} has no rows".format(file))
        rgb, rgcLen, rgiChunk, lookup = Encode(rows)
        cTable = len(rgcLen)
        if enum:
            header.append("enum {} {{".format(enum))
            header += ["    {} = {},".format(row.name, fmtId.format(row.id)) for row in rows]
            header += ["};", ""]
        else:
            # Planet names have no IDs; code needs only how many there are.
            header += ["enum PlanetNameCount {", "    cPlanetName = {},".format(cTable), "};", ""]
        body = ["// " + GENERATED.format(file), '#include "{}"'.format(include), ""]
        if fArgs:
            rgcArgs = [0] * cTable
            for row in rows:
                rgcArgs[row.id] = row.args
            body.append(FormatArray("char rgcMsgArgs[{}]".format(cTable), rgcArgs))
        body.append(FormatArray("uint8_t ac{}[{}]".format(tag, cTable), rgcLen))
        body.append(FormatArray("char a{}Cmpr[{}]".format(tag, len(rgb)), [Signed(b) for b in rgb]))
        body.append(FormatArray("int16_t ai{}ChunkOffset[{}]".format(tag, len(rgiChunk)), rgiChunk))
        body.append(FormatArray("char rg{}LookupTable[{}]".format(tag, len(lookup)), lookup))
        outputs[output] = "\n".join(body)
    header += ["#endif", ""]
    outputs["textids.h"] = "\n".join(header)
    os.makedirs(outdir, exist_ok=True)
    for name, text in outputs.items():
        WriteIfChanged(os.path.join(outdir, name), text)


def ListUnreferenced():
    """Print rows whose names no C source uses and no @range covers."""
    sources = []
    for name in sorted(os.listdir(ROOT)):
        if name.endswith((".c", ".h")):
            with open(os.path.join(ROOT, name), encoding="latin-1") as f:
                sources.append(f.read())
    used = set(re.findall(r"\bid[smt][A-Za-z0-9_]+", "\n".join(sources)))
    for file, tag, prefix, enum, fmtId, fArgs, output, include in TABLES:
        if not prefix:
            continue
        rows, ranges = ParseTable(os.path.join(HERE, file), prefix, fArgs)
        inRange = {row.id for r in ranges for row in r[3]}
        for row in rows:
            if row.name not in used and row.id not in inRange:
                print('text/{}:{}: {} "{}"'.format(file, row.line, row.name, row.text))


def main(argv):
    try:
        if argv == ["--unreferenced"]:
            ListUnreferenced()
        elif len(argv) == 1 and not argv[0].startswith("-"):
            Generate(argv[0])
        else:
            sys.stderr.write(__doc__.split("\n\n")[1] + "\n")
            return 2
    except TextError as e:
        sys.stderr.write("textgen: {}\n".format(e))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
